In [2]:
"""
 in this exercise, we are going to use the argmax() function to find the position of the maximum value in a given matrix along the axes 0 and 1
"""

'\n in this exercise, we are going to use the argmax() function to find the position of the maximum value in a given matrix along the axes 0 and 1\n'

In [3]:
import tensorflow as tf
X = tf.Variable([[91,12,15],
                [11,88,21],
                [90,87,75]])
tf.print(X)

[[91 12 15]
 [11 88 21]
 [90 87 75]]


2022-05-13 07:35:07.257614: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
# print shape of X
X.shape

TensorShape([3, 3])

In [5]:
# use argmax() to find the positions of the max values while keeping axis as 0
tf.print(tf.argmax(X, axis=0))

[0 1 2]


In [6]:
# use argmax() to find the positions of the max values while keeping axis as 1
tf.print(tf.argmax(X, axis=1))

[0 1 0]
