In [1]:
# import tensorflow library and create two variables, X & Y, as matrices
import tensorflow as tf
X = tf.Variable([[1,2,3],[4,5,6]]) # 2x3
Y = tf.Variable([[7,8], [9,10],[11,12]]) # 3x2

"""
matrix multiplication is possible due to C = R. That is the number of columns (C) in the first matrix should be equal to the number
of rows (R) in the second matrix. In this case we have 2 = 2.
"""

2022-05-13 06:44:53.800165: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


'\nmatrix multiplication is possible due to C = R. That is the number of columns (C) in the first matrix should be equal to the number\nof rows (R) in the second matrix. In this case we have 2 = 2.\n'

In [2]:
# print the values of the matrices
tf.print(X)

[[1 2 3]
 [4 5 6]]


In [3]:
tf.print(Y)

[[7 8]
 [9 10]
 [11 12]]


In [4]:
# perform matrix multiplication by calling tf.matmul() and passing X,Y as parameters
c1 = tf.matmul(X,Y)
tf.print(c1)

[[58 64]
 [139 154]]


In [7]:
# perform matrix multiplication by changing the order of the matrices
c2 = tf.matmul(Y,X)
tf.print(c2)

[[39 54 69]
 [49 68 87]
 [59 82 105]]
