In [1]:
import tensorflow as tf

In [2]:
# create a tensor called A from the first matrix
A = tf.Variable([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

2022-05-18 07:12:20.377369: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [3]:
# create a tensor called B from the second martix
B = tf.Variable([[1, 0, -1], [1, 0, -1], [1, 0, -1]])
B

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 1,  0, -1],
       [ 1,  0, -1],
       [ 1,  0, -1]], dtype=int32)>

In [4]:
# perform element-wise multiplication on A & B using tf.math.multiply(A, B)
mult_out = tf.math.multiply(A, B)
mult_out

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  0, -3],
       [ 4,  0, -6],
       [ 7,  0, -9]], dtype=int32)>

In [5]:
# perform element-wise sum on mult_out using tf.math.reduce_sum()
conv_out = tf.math.reduce_sum(mult_out)
conv_out

<tf.Tensor: shape=(), dtype=int32, numpy=-6>