#### Exercise 5.02: Implementing the Forward Pass of a Simple RNN Using TensorFlow

In [7]:
import numpy as np
import tensorflow as tf
np.random.seed(0)
tf.random.set_seed(0)

In [8]:
num_inputs = 2 # number of inputs
num_neurons = 3 # number of neurons

We will have two inputs at each time step. Let's call them xt0 and xt1.

Define the variables for the weight matrices. We need two of them – one for the feedforward weights and another for the recurrent weights. Initialize them randomly:

In [9]:
Wf = tf.Variable(
    tf.random.normal(shape=[num_inputs, num_neurons]) # 2,3
)

Wr = tf.Variable(
    tf.random.normal(shape=[num_neurons, num_neurons]) # 3,3
)

2022-06-24 06:13:56.732956: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Notice the dimensions for the recurrent weights – it is a square matrix, with as many rows/columns as the number of neurons in the hidden layer.

Add the bias variable (to make the activations fit the data better), with as many zeros as the number of neurons in the hidden layer:

In [10]:
b = tf.Variable(
    tf.zeros([1,num_neurons])
)

Create the data – three examples for xt0 (two inputs, three examples) as [[0,1], [2,3], [4,5]] and xt1 as [[100,101], [102,103], [104,105]] – as numpy arrays of the float32 type (consistent with dtype for TensorFlow's default float representation):

In [11]:
xt0_batch = np.array(
    [
        [0,1],
        [2,3],
        [4,5]
    ]
).astype(np.float32)

xt1_batch = np.array(
    [
        [100,101],
        [102,103],
        [104,105]
    ]
).astype(np.float32)

Define a function named forward_pass to apply a forward pass to the given data, that is, xt0, xt1. Use tanh as the activation function. The output at t=0 should be derived from Wf and xt0 alone. The output at t=1 must use yt0 with the recurrent weights, Wf, and use the new input, xt1. The function should return outputs at the two time steps:

In [12]:
def forward_pass(xt0, xt1):
    yt0 = tf.tanh(tf.matmul(xt0, Wf) + b)
    yt1 = tf.tanh(tf.matmul(yt0, Wr) + tf.matmul(xt1, Wf) + b)
    return yt0, yt1

Note that there is no recurrent weight here at time step 0; it comes into play only after the first time step.

Perform the forward pass by calling the forward_pass function with the created data (xt0_batch, xt1_batch) and put the output into variables, yt0_output and yt1_output:

In [13]:
yt0_output, yt1_output = forward_pass(xt0_batch, xt1_batch)

In [14]:
tf.print(yt0_output)

[[-0.776318431 -0.844548464 0.438419849]
 [-0.0857750699 -0.993522227 0.516408086]
 [0.698345721 -0.999749422 0.586677969]]


In [15]:
tf.print(yt1_output)

[[1 -1 0.999998629]
 [1 -1 0.999998331]
 [1 -1 0.999997377]]


We can see that the final output at time t=1 is a 3x3 matrix – representing the outputs for the three neurons in the hidden layer for the three instances of data.