In [1]:
"""
 In this exercse we will reshape a [5,4] matrix into the shape of [5,4,1]
 using the reshape() function.
"""

'\n In this exercse we will reshape a [5,4] matrix into the shape of [5,4,1]\n using the reshape() function.\n'

In [2]:
import tensorflow as tf

In [3]:
A = tf.Variable([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16],
                [17,18,19,20]])

2022-05-13 07:01:49.719162: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
# print variable A
tf.print(A)

[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [5]:
# print shape of A
A.shape

TensorShape([5, 4])

In [6]:
# Currently A has a rank of 2. We will be using reshape() to change it's rank to 3
tf.print(tf.reshape(A,[5,4,1]))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


In [7]:
# assign new shape to A
A = tf.reshape(A,[5,4,1])
A.shape

TensorShape([5, 4, 1])