In [1]:
# import required libraries
import tensorflow as tf

import pandas as pd

from sklearn.metrics import confusion_matrix, accuracy_score

import matplotlib.pyplot as plt

%matplotlib inline

from pandas import get_dummies

In [2]:
# create an instance of the MNIST dataset
mnist = tf.keras.datasets.mnist

In [3]:
# load MNIST dataset's train and test data
(train_features, train_labels), (test_features, test_labels) = mnist.load_data()

In [4]:
# normalize the data
train_features, test_features = train_features/255.0, test_features/255.0

In [5]:
# flatten the 2D images into row matrices
# So, a 28 × 28 pixel gets flattened to 784 using the reshape function
x = tf.reshape(train_features, [60000, 784]) # 60000 is the number of observations in the train set

2022-05-15 08:02:59.286349: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
# create a variable with the features and type cast into float32
x = tf.Variable(x)
x = tf.cast(x, tf.float32)

In [7]:
# create a one-hot encoding of the labels and transform into a matrix
y_hot = get_dummies(train_labels)
y = y_hot.values

In [8]:
# create single-layer neural network with 10 neurons and train for 1000 iterations
number_of_features = 784
number_of_units = 10 # nuerons equals to classes

# weights and bias
weight = tf.Variable(tf.zeros([number_of_features, number_of_units]))
bias = tf.Variable(tf.zeros([number_of_units]))

# define perceptron
def perceptron(x):
    z = tf.add(tf.matmul(x, weight), bias) # input function
    output = tf.nn.softmax(z) # activation function
    return output

# optimizer
optimizer = tf.optimizers.Adam(.01)

# define training
def train(i):
    for n in range(i):
        loss = lambda:abs(tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=perceptron(x))))
        optimizer.minimize(loss, [weight, bias])
        
# train perceptron
train(1000)

In [9]:
tf.print(weight)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
# prepare the test data to measure the accuracy
test = tf.reshape(test_features, [10000, 784]) # 10000 is the number of observations provided for testing set, 784 is flattend 28x28 image
test = tf.Variable(test)
test = tf.cast(test, tf.float32)
test_hot = get_dummies(test_labels)
test_matrix = test_hot.values

In [11]:
# run the predictions by passing the test data through the network
ypred = perceptron(test)
ypred = tf.round(ypred)

# calculate accuracy 
accuracy_score(test_hot, ypred)

0.9304