In [1]:
# import package(s)
import tensorflow as tf

In [4]:
# set the input data and labels of the OR table in TensorFlow
X = tf.Variable([[0.,0.],
                 [0.,1.],
                 [1.,0.],
                 [1.,1.]], 
                 dtype=tf.float32)

2022-05-14 08:38:33.798990: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
print(X)

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)>


In [6]:
# Set actual labels in TensorFlow and use reshape() on y vector into a 4x1 matrix
y = tf.Variable([0,1,1,1], dtype=tf.float32)
y = tf.reshape(y, [4,1])
print(y)

tf.Tensor(
[[0.]
 [1.]
 [1.]
 [1.]], shape=(4, 1), dtype=float32)


In [7]:
print(X.shape)
print(X.shape[1])

(4, 2)
2


In [8]:
# design parameters of a perceptron
"""
Number of neurons (units) = 1
Number of features (inputs) = 2 (number of examples x number of features)
"""

# activation function will be sigmoid function since we are doing binary classification
NUM_FEATURES = X.shape[1]
OUTPUT_SIZE = 1

In [9]:
# define the connections weight matrix in TensorFlow
W = tf.Variable(tf.zeros([NUM_FEATURES, OUTPUT_SIZE]),dtype=tf.float32)
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>


In [10]:
# variable for bias
B = tf.Variable(tf.zeros([OUTPUT_SIZE, 1]), dtype=tf.float32)
print(B)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.]], dtype=float32)>


In [11]:
# define function called perceptron to get the output
def perceptron(X):
    z = tf.add(tf.matmul(X, W), B)
    output = tf.sigmoid(z)
    return output
print(perceptron(X))

tf.Tensor(
[[0.5]
 [0.5]
 [0.5]
 [0.5]], shape=(4, 1), dtype=float32)


In [12]:
tf.print(W,B)

[[0]
 [0]] [[0]]
